### ISSUE TITLE
デザインの微調整依頼

### ISSUE THREAD

**Issue by Sen-Megaten4649** [2025-Winter-Hackathon-F-team/2025winterF#120]
バックエンドチームからの依頼受付

- [x] home.htmlのToDo達成後文字表示
- [x] home.html ToDoの数　5個/1pあたりに修正
- [ ] todo_detail.htmlの達成ボタン/固定文字位置修正
- [ ] setup.htmlの誕生日カラム　文字頭修正

![Image](https://github.com/user-attachments/assets/7462af3c-e535-4b0d-ac5e-a71015804e73)
↓　base.htmlとcssでまとめて修正できる

```
<body>
    <!-- hide_headerの値を取得するが、非表示にする -->
    <span id="hide-header" style="display: none;">
        {% block hide_header %}{% endblock hide_header %}
    </span>

    {% if hide_header != "True" %}
        {% include "header.html" %}
    {% endif %}

    {% block content %}{% endblock content %}
    {% block script %}{% endblock script %}
</body>
```

```
#hide-header {
    display: none;
}
```

**Comment by kageyamatakumu** [comment]
- [x] `home.html` の月目標達成後文字表示
- [x] `home.html` のCSSを `home.css` に移行
- [x] ログイン画面の入力エリアの後ろに変な文字（「true」）がある？

**Comment by kageyamatakumu** [comment]
## `feedback_good.html` と `feedback.html` にヘッダー部分がずれている？

 `padding: 20px;` を削除したら良い？他に考慮しないといけないことがある？
```css
body {
    background: url("../images/feedback_good.png") no-repeat center center/cover;
    background-attachment: fixed;
    background-size: cover;
    color: #454749;
    font-family: "Kaisei Opti", serif;
    min-height: 100svh;
    padding: 20px; // ⭐️
    overflow: hidden; /* 溢れた画像を切り取って非表示=>スクロールを防ぐ */
}
```
